feat: arconnect components v2
th8ta/ArConnect pull request #244
Opened 2024-03-01 21:44 UTC by elehmandevelopment

This PR integrates v2 components into ArConnect replacing all existing components. 

It includes new components for:
- Buttons
- Inputs
- List Items
- Selects
- Tooltips
- Modal Popups

2024-03-06 15:46 UTC, nicholaswma requested changes
bg color for search bar in currency needs to be updated

2024-03-07 01:45 UTC, 7i7o approved these changes
tACK 🚀

2024-03-19 02:35 UTC, 7i7o reviewed
Left comments in each file.

AO Tokens in settings are still using BaseElement, so thay don't look the same as Warp tokens

2024-03-19 02:35 UTC, 7i7o commented on src/components/dashboard/list/TokenListItem.tsx
> +import BaseElement from "./BaseElement";
Wasn't BaseElement replaced by ListItem?
We shouldn't be using it for the AO tokens

2024-03-19 02:35 UTC, 7i7o commented on src/components/dashboard/Contacts.tsx
> +import { ButtonV2, Spacer, useInput } from "@arconnect/components";
`ButtonV2` replaced `IconButtton`, so the `IconButton` import should be removed

2024-03-19 02:35 UTC, 7i7o commented on src/components/dashboard/Reset.tsx
> +    props.displayTheme === "light" ? "#F58080" : "#8C1A1A"};
Same thing Nick mentioned, we should get some clarity on what color to use from the theme here so we don't hardcode the colors

2024-03-19 02:35 UTC, 7i7o commented on src/components/dashboard/subsettings/AddWallet.tsx
>    Text,
Still importing `Button` and `Input` in the previous 2 lines

2024-03-19 02:35 UTC, 7i7o commented on src/components/dashboard/subsettings/AppSettings.tsx
>            <InputWithBtn>
`InputWithBtn` component in the `arlocal` folder (and some other files in that folder) still use `Button` and `Input`

2024-03-19 02:35 UTC, 7i7o commented on src/components/dashboard/subsettings/AppSettings.tsx
> +              <InputV2
Inside this component we are using `IconButton` that still uses `Button`, as well as `Recipient.tsx` and `SliderMenu.tsx` in the components folder

2024-03-19 02:35 UTC, 7i7o commented on src/components/popup/WalletHeader.tsx
> +      {/* @ts-ignore */}
Why are we ignoring typescript errors?

2024-03-19 02:35 UTC, 7i7o commented on src/routes/auth/connect.tsx
> +  height: 22px;
Let's user `rem` units for a11y

2024-03-19 02:35 UTC, 7i7o commented on src/routes/auth/connect.tsx
> +  padding: 13.5px 15px;
Same with `rem` units

2024-03-19 02:35 UTC, 7i7o commented on src/routes/popup/send/index.tsx
>    Input,
`Button` and `Input` still in use, `ButtonV2` imported but not used?

2024-04-03 16:52 UTC, nicholaswma approved these changes

2024-04-03 16:52 UTC, nicholaswma commented on src/components/dashboard/Contacts.tsx
> +import { ButtonV2, Spacer, useInput } from "@arconnect/components";
couldn't comment it out but just remove 
`import { IconButton } from "~components/IconButton";`

2024-04-03 16:52 UTC, nicholaswma commented on src/components/dashboard/Wallets.tsx
> +import { ButtonV2, Spacer, useInput } from "@arconnect/components";
remove:
import { PlusIcon } from "@iconicicons/react";
import { IconButton } from "~components/IconButton";

2024-04-03 16:52 UTC, nicholaswma commented on src/components/dashboard/list/WalletListItem.tsx
> +      <ListItem
type error on dragcontrols - I think this is probably caused by the mismatch in framer versions, we can investigate later on

2024-04-03 16:52 UTC, nicholaswma commented on src/components/dashboard/Contacts.tsx
> +const AddContactButton = styled(ButtonV2).attrs({
Should this be primary?

2024-04-03 16:52 UTC, nicholaswma commented on src/components/dashboard/Wallets.tsx
> +const AddWalletButton = styled(ButtonV2).attrs({
Should this be primary?

2024-04-03 16:53 UTC, 7i7o approved these changes
LGTM 🚀

2024-04-03 16:54 UTC, merged