refactor: Show network connectivity error tooltip
th8ta/ArConnect pull request #406
Opened 2024-06-24 13:03 UTC by pawanpaudel93

## Summary

This PR adds the network connectivity tooltip for AO tokens when the balance fetch is failed.

<img src="https://github.com/arconnectio/ArConnect/assets/11836100/1179a7c8-478f-42ef-b267-3565a8050fd8" width="400" />

2024-06-24 14:00 UTC, 7i7o requested changes

2024-06-24 14:00 UTC, 7i7o commented on src/components/popup/Token.tsx
> +      Your ISP or VPN is blocking access to AO.
Let's i18n these two messages

2024-06-24 15:26 UTC, pawanpaudel93 commented on src/components/popup/Token.tsx
> +      Your ISP or VPN is blocking access to AO.
Sure, I will do that.

2024-06-25 11:07 UTC, pawanpaudel93 commented
@7i7o since we cannot get the same fetch error status as we see in the browser, we don't know if it was failed due to ISP/VPN blocking ao. I did add a common fetch error check that occurs on if fetch is failed but do you have idea on how we can make it better ?

2024-06-25 15:33 UTC, 7i7o commented
> @7i7o since we cannot get the same fetch error status as we see in the browser, we don't know if it was failed due to ISP/VPN blocking ao. I did add a common fetch error check that occurs on if fetch is failed but do you have idea on how we can make it better ?

Actually those are the best error messages we have from the users that experienced the problem

2024-06-25 15:33 UTC, 7i7o approved these changes
tACK 👍

2024-07-01 21:05 UTC, merged