fix: Update logic for showing `Add $AR to get started` #472
th8ta/ArConnect pull request #498
Opened 2024-10-15 16:51 UTC by pawanpaudel93

## Summary

This PR updates the logic for displaying the message **"Add $AR to get started."**

## How to Test

1. Prepare at least one wallet from each of the following categories:
   - **Wallet with AR:** Contains a balance of AR tokens.
   - **Wallet without AR:** Contains balances of other tokens but no AR.
    - **Wallet without AR and other tokens:** Contains no balances of AR and other tokens.

2. **Testing Wallet Switching and Popup:**
   - Make sure this is done with both scenarios: **all assets** and **zero assets** (delete all assets).
   - Open the ArConnect popup and switch between wallets to observe the UI changes.
   - Open the ArConnect popup for each wallet individually to observe the UI for all wallet types.

3. Ensure all issues from [#472](https://github.com/arconnectio/ArConnect/issues/472) have been resolved.

2024-10-16 15:59 UTC, 7i7o requested changes
The second case, a wallet with AO tokens and NO AR tokens, when you remove all AO and Warp tokens it shows the Add $AR and that doesn't let you go to "View All" page to see if you have any tokens that you didn't add

2024-10-16 18:04 UTC, pawanpaudel93 commented
@7i7o should we change the conditions on when to show `Add $AR to get started` as for the scenario you explained above we might have to check balances for all the tokens that aren't added but discovered in the View all ?

2024-10-17 10:09 UTC, 7i7o commented
> @7i7o should we change the conditions on when to show `Add $AR to get started` as for the scenario you explained above we might have to check balances for all the tokens that aren't added but discovered in the View all as well ?

We can still show the banner while triggering that fetch in the background, and hide the banner if we find some tokens. Wdyt?
Another option is to change the UI for the "View All Assets" to be accesible even when we haven't found any balance yet

2024-10-18 17:56 UTC, nicholaswma approved these changes

2024-10-18 17:57 UTC, merged